title: Bioregistry
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  An integrative registry of biological databases, ontologies, and nomenclatures.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
