name: "Register new prefix"

on:
  workflow_dispatch:
  issues:
    types: [ opened ]

jobs:
  register:
    name: Register new prefix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .
      - name: Update
        id: update
        run: |
          OUTPUT=$(python -m bioregistry.gh.new_prefix --dry)
          echo $OUTPUT
          echo "::set-output name=BR_BODY::$(echo $output | grep Closes)"
          echo "::set-output name=BR_TITLE::$(echo $output | grep Add)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch-suffix: short-commit-hash
          body: ${{ steps.update.outputs.BR_BODY }}
          title: ${{ steps.update.outputs.BR_TITLE }}
