name: Release
on:
  push:
    tags:
      - 'v[0-9]{1-4}+.[0-9]{1-4}+.[0-9]{1-4}+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
